spring.application.name=lead_finder

spring.datasource.url=jdbc:mysql://localhost:3306/lead_finder
spring.datasource.username=root
spring.datasource.password=Anmolgiri
spring.jpa.hibernate.ddl-auto=update


selenium.chrome.headless=false

selenium.chrome.user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

selenium.download.directory=${user.home}/leadfinder-downloads

selenium.chrome.window-size=1920,1080
selenium.timeout.implicit=10
selenium.timeout.page-load=30


# ========================== ASYNC CONFIG (Selenium Scraping) ==========================
async.core-pool-size=8
async.max-pool-size=20
async.queue-capacity=100
async.keep-alive-seconds=60
async.thread-name-prefix=LeadFinder-Scraper-
async.allow-core-thread-timeout=true

# Recommended for production (adjust based on your server RAM)
# Each Chrome instance ? 300-600 MB ? don't go too high!

# Export settings
export.directory=${user.home}/leadfinder-exports

# Job cleanup (used by CleanupScheduler)
job.cleanup.hours=24